library(dplyr)

setwd("/home1/jialh/mNetwork/MNDnetwork/PRJEB17784/SparCC/ResultsSparCC_Control_filtered")

data <- read.csv("00merge_sparcc_correlation_matrix.csv", header = TRUE)
print(data[1:5, 1:5])
print(dim(data))
print(colnames(data))

data=data[order(abs(data$coefficient),decreasing = T),] #edge list with real coefficient and fake coefficient generated by 100x permutation by sparcc
print(data[1:5, 1:5])
data$fdr=NA
print(data[1:3, 4:103])
print(data$coefficient[1])
print()

#print(length(which(abs(data[,4:103])>=abs(data$coefficient)[1])))

for(i in 1:nrow(data)){
  data$fdr[i]=(length(which(abs(data[,4:103])>=abs(data$coefficient)[i]))/100)/i #3:102 columns represent fake coefficient generated by 100x permutation
}

print(data$fdr[1:500])
data_FDR <- subset(data, fdr<0.05)
print(dim(data_FDR))

write.csv(data_FDR[,c(1,2,3,104)], "01network_edges_pass_FDR.csv", row.names=FALSE)
